### PR TITLE
Created Portfolio 02 Folder

### LINKED ISSUE #39: Portfolio Website
### Description

I want to work on Portfolio 2 
Kindly assign me this issue I am a contributor in GSSoC'22

### Screenshots

_No response_

### Additional information

Portfolio 1 is already there

### PR DESCRIPTION
**Pull request by mohammadshaad**
Fixes #39 
<h1 align="center">Designed Portfolio 02</h1><br>

- Added a .gitignore folder and moved .DS_Store file to .gitignore
- Added .fig file along with the .PNG file of the website

Portfolio02

### CODE REVIEW

**Comment by mohammadshaad** [comment]
Kindly check and accept the pull request

**Comment by GovindSingh9447** [comment]
Well done 👍

**Comment by mohammadshaad** [comment]
Thank You @GovindSingh9447

**Comment by mohammadshaad** [comment]
@GovindSingh9447 rename the label with level and GSSoC because the leaderboard is not showing my PR score

**Comment by GovindSingh9447** [comment]
> @GovindSingh9447 please rename the label with level and GSSoC because the leaderboard is not showing my PR score

Done.

**Comment by mohammadshaad** [comment]
I still can't see it @GovindSingh9447

**Comment by mohammadshaad** [comment]
@GovindSingh9447 Can you please correct the label on this PR as it is not showing this PR in the leaderboard.
I guess it is should be Level 2 or something like that you know it right. Kindly correct it asap.

**Comment by GovindSingh9447** [comment]
> @GovindSingh9447 Can you please correct the label on this PR as it is not showing this PR in the leaderboard. I guess it is should be Level 2 or something like that you know it right. Kindly correct it asap.

@Jaideep25-tech have a look.

**Pull request merged**
