### PR TITLE
Adding .fig file and preview for readme

### PR DESCRIPTION
**Pull request by Gaurav4code**

### CODE REVIEW

**Review by garvitraj — APPROVED** [review]
Good work

**Comment by garvitraj** [comment]
@Gaurav4code pls add the .fig file asap in the folder and follow the folder structure as I cant find the .fig file
do it on imp basis

**Comment by garvitraj** [comment]
i m reverting back the pull request add .fig file like other folders and make a new PR @Gaurav4code

**Comment by Gaurav4code** [comment]
Ok, I am undoing the mistakes  .

**Comment by Gaurav4code** [comment]
Created new PR with required folder structure.

**Pull request merged**
