### PR TITLE
added neumorphism portfolio design

### PR DESCRIPTION
**Pull request by suyogkokaje**
<h2> Desktop View </h2>
<h3> Home </h3>
Screenshot-1373
<h3> About </h3>
Screenshot-1383
<h3> Portfolio </h3>
Screenshot-1376
<h3> Contact </h3>
Screenshot-1377
<h2> Mobile View </h2>
<h3> Home </h3>
Screenshot-1378
<h3> About </h3>
Screenshot-1380
<h3> Portfolio </h3>
Screenshot-1381
<h3> Contact </h3>
Screenshot-1382
<h2> Dark Mode </h2>
Screenshot-1374

### CODE REVIEW

**Comment by suyogkokaje** [comment]
@GovindSingh9447 please have a look.

**Comment by GovindSingh9447** [comment]
Outstanding work

**Comment by suyogkokaje** [comment]
> Outstanding work

Thanks 😅

**Comment by GovindSingh9447** [comment]
@suyogkokaje have you created this portfolio on ReactJs?

**Comment by suyogkokaje** [comment]
yes @GovindSingh9447

**Pull request merged**
